# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180120_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.TextField(default=''),
        ),
    ]
